FROM jenkins/ssh-agent:jdk11
USER root
SHELL ["/bin/bash", "-c"]
RUN apt-get update -y && apt upgrade -y
RUN apt install -y git ca-certificates curl gnupg lsb-release sudo

#Install Docker in Docker
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt update -y
RUN apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
RUN apt install docker-compose -y

#PRIVILEGE
RUN usermod -a -G docker jenkins
RUN usermod -a -G root jenkins
RUN usermod -a -G sudo jenkins
RUN cat /dev/null > /etc/sudoers
RUN echo 'Defaults        env_reset' >> /etc/sudoers
RUN echo 'Defaults        mail_badpass' >> /etc/sudoers
RUN echo 'Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"' >> /etc/sudoers
RUN echo 'root    ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN echo 'jenkins ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN echo '# Allow members of group sudo to execute any command' >> /etc/sudoers
RUN echo '%sudo   ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN echo '# See sudoers(5) for more information on "@include" directives:' >> /etc/sudoers
RUN echo '@includedir /etc/sudoers.d' >> /etc/sudoers

RUN apt-get update -y && apt upgrade -y
